In [2]:
import numpy as np

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

In [11]:
A/A.sum(axis=0)*100

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

In [17]:
a = np.random.randn(5,1)

In [20]:
np.dot(a.T, a)

array([[ 1.85110168]])

In [23]:
img = np.random.randn(32,32,3)

In [25]:
img.reshape(32*32*3,1)

array([[ 0.65063719],
       [-1.61548576],
       [ 0.51539369],
       ..., 
       [ 0.12703582],
       [-1.04408582],
       [ 0.04033332]])

In [29]:
a = np.random.randn(12,15)
b = np.random.randn(15,45)

c = np.dot(a,b)

In [30]:
c.shape

(12, 45)